In [117]:
import statistics 
import numpy as np
from sklearn.datasets import make_classification 
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from scipy import stats
from scipy.spatial import distance

In [118]:
x=[]
o=[]
p=[]
f = open("iris.Data.txt", "r")
b=f.readlines()
i=0
X1 = np.empty(0)
for j in range(len(b)):
    s=b[j].split(",")
    o.append(s[:4])
    p.append(s[4:5])
    if(i<141):
        for w in range(4):
            X1=np.append(X1,(float(o[i][w])))
    i+=1

X1=X1.reshape(141,4)
f.close()

In [119]:
Y1=[]
for e in range(140):
    if(p[e] == ['Iris-setosa\n']):
        Y1.append([1,0,0])
       
    if(p[e] == ['Iris-versicolor\n']):
        Y1.append([0,1,0])
       
    if(p[e] == ['Iris-virginica\n']):
        Y1.append([0,0,1])
    


In [120]:
i=0
l=[]
d=[]
f = open("Ydata.txt", "r")
b=f.readlines()
for j in range(len(b)):
    
    #print(b[j])
    #print((b[j][:15]))
    s=b[j].split(",")
    l.append(s[:4])
    d.append(s[4:5])
    if(i<9):
        for w in range(4):
            l[i][w]=float(l[i][w])
    i+=1

X2=np.array(l)
f.close()

In [121]:
Y2=[]
for e in range(9):
    if(d[e] == ['Iris-setosa\n']):
        Y2.append([1,0,0])
       
    if(d[e] == ['Iris-versicolor\n']):
        Y2.append([0,1,0])
       
    if(d[e] == ['Iris-virginica\n']):
        Y2.append([0,0,1])
    


# Calculate euclidean distance

In [122]:
def caldist(x1,Xtest):
    distances=[]
    ds=[]
    for u in Xtest:
        for r in range(len(x1)-1):
            dst = distance.euclidean(x1[r], u)
            ds.append(dst)
        distances.append(ds)
        ds=[]
    
    return distances


In [123]:
k=4
def dissort(dis):
    sortdis=[]
    for u in dis:
        sortdis.append((np.argsort(u))[0:k])
    return sortdis

In [124]:
def predict(ls, Y_in ):
    preds=[]
    y=[]
    for i in range(len(ls)):
        for b in ls[i]:
            y.append(Y_in[b])  
        preds.append(stats.mode(y)[0])
        y=[]
    
    return preds

In [125]:
def accur(Y_pred, Y_test):
    b = 0
    acc = 0
    num=len(Y_pred)
    c = num
    print(c)
    for i in range(len(Y_pred)):
        b = distance.euclidean(Y_pred[i], Y_test[i])
        if(b!=0):
            c -= 1
    acc = (c/num)*100
    return acc
    

In [126]:
l=caldist(X1,X2)
m= dissort(l)
t=predict(m,Y1)
print(t)
s = accur(t,Y2)
print(s)

[array([[0, 0, 1]]), array([[0, 0, 1]]), array([[0, 0, 1]]), array([[0, 1, 0]]), array([[0, 1, 0]]), array([[0, 1, 0]]), array([[1, 0, 0]]), array([[1, 0, 0]]), array([[1, 0, 0]])]
9
100.0


# Minowski distance 

In [1]:
def caldistmin(x1,Xtest,p):
    distances=[]
    ds=[]
    for u in Xtest:
        for r in range(len(x1)-1):
            dst = distance.minkowski(x1[r], u,p)
            ds.append(dst)
        distances.append(ds)
        ds=[]
    
    return distances

In [15]:
L=caldistmin(X1,X2,10)
M= dissort(L)
T=predict(M,Y1)
print(T)
s = accur(T,Y2)
print(s)

[array([[0, 0, 1]]), array([[0, 0, 1]]), array([[0, 0, 1]]), array([[0, 1, 0]]), array([[0, 1, 0]]), array([[0, 1, 0]]), array([[1, 0, 0]]), array([[1, 0, 0]]), array([[1, 0, 0]])]
9
100.0


# calculate mahalanobis distance

In [190]:
#calc inverse covariance of x
cov = np.cov(X1.T)
inv = np.linalg.inv(cov)
print(inv)

[[ 10.49806841  -6.71837952  -7.26707883   5.54994247]
 [ -6.71837952  11.00150952   6.49723271  -6.32930355]
 [ -7.26707883   6.49723271   9.96757171 -14.43211674]
 [  5.54994247  -6.32930355 -14.43211674  27.5887272 ]]


In [112]:
def calmdist(x1,Xtest,inv):
    distances=[]
    ds=[]
    for u in Xtest:
        for r in range(len(x1)-1):
            dst = distance.mahalanobis(x1[r], u, inv)
            ds.append(dst)
        distances.append(ds)
        ds=[]
    
    return distances

In [192]:
E=calmdist(X1,X2,inv)
n= dissort(E)
t1=predict(n,Y1)
print(t1)
s1 = accur(t1,Y2)
print(s1)

[array([[0, 0, 1]]), array([[0, 0, 1]]), array([[0, 0, 1]]), array([[0, 1, 0]]), array([[0, 1, 0]]), array([[0, 1, 0]]), array([[1, 0, 0]]), array([[1, 0, 0]]), array([[1, 0, 0]])]
9
100.0


# dataset 2

note: in this dataset there are 16 cases out of the 699 that have a missing value.this issue was resolved by setting the missing value to zero

In [16]:
x=[]
o=[]
p=[]
f = open("cancer/training.txt", "r")
b=f.readlines()
print(len(b))
i=0
Xc1 = np.empty(0)
for j in range(len(b)):
    lens=len(b[j])
    s=b[j][:lens-2]
    o.append(s.split(","))
    p.append(int(b[j][lens-2:lens]))
    #print(s)
print(len(o))
for u in o:
    q=len(u)
    x.append(u[1:q-1])

#print(x)

l=[]
for y in x:
    for w in y:
        if (w=='?'):
            l.append(0)
        else:
            l.append(int(w))

Xc1=np.array(l)
print(Xc1.shape)
Xc1=Xc1.reshape(679,9)
Yc1=p
f.close()


679
679
(6111,)


In [17]:
x=[]
o=[]
p=[]
f = open("cancer/tests.txt", "r")
b=f.readlines()
Xc_t1 = np.empty(0)
for j in range(len(b)):
    lens=len(b[j])
    s=b[j][:lens-2]
    o.append(s.split(","))
    p.append(int((b[j][lens-2:lens-1])))

for u in o:
    q=len(u)
    x.append(u[1:q-1])
l=[]
for y in x:
    for w in y:
        if (w=='?'):
            l.append(0)
        else:
            l.append(int(w))

Xc_t1=np.array(l)
Xc_t1=Xc_t1.reshape(20,9)
Yc_t1=p
print(Xc_t1)
print(Yc_t1)

f.close()

[[ 1  1  1  1  1  1  3  1  1]
 [ 2  1  1  1  2  1  2  1  1]
 [ 5  3  3  3  2  3  4  4  1]
 [ 2  1  3  2  2  1  2  1  1]
 [ 5  1  1  1  2  1  2  1  1]
 [ 6 10 10 10  4 10  7 10  1]
 [ 1  2  2  1  2  1  1  1  1]
 [ 1  1  1  3  2  1  1  1  1]
 [ 5 10 10 10 10  2 10 10 10]
 [ 5 10 10 10  4 10  5  6  3]
 [ 5  1  1  1  2  1  3  2  1]
 [ 1  1  1  1  2  1  1  1  1]
 [ 1  1  1  1  2  1  1  1  1]
 [ 1  1  1  1  2  1  1  1  1]
 [ 8  7  8  5 10 10  7  2  1]
 [ 1  1  1  1  2  1  2  1  1]
 [ 5  2  2  2  2  2  3  2  2]
 [ 2  3  1  1  5  1  1  1  1]
 [ 3  2  2  3  2  3  3  1  1]
 [10 10 10  6  8  4  8  5  1]]
[2, 2, 4, 2, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4]


In [18]:
l=caldist(Xc1,Xc_t1)
m= dissort(l)
t=predict(m,Yc1)
print(t)
s = accur(t,Yc_t1)
print(s)

[array([2]), array([2]), array([2]), array([2]), array([2]), array([4]), array([2]), array([2]), array([4]), array([4]), array([2]), array([2]), array([2]), array([2]), array([4]), array([2]), array([2]), array([2]), array([2]), array([4])]
20
95.0


In [21]:
l=caldistmin(Xc1,Xc_t1,10)
m= dissort(l)
t=predict(m,Yc1)
print(t)
s = accur(t,Yc_t1)
print(s)

[array([2]), array([2]), array([2]), array([2]), array([2]), array([4]), array([2]), array([2]), array([4]), array([4]), array([2]), array([2]), array([2]), array([2]), array([4]), array([2]), array([2]), array([2]), array([2]), array([4])]
20
95.0


# dataset 2 mahalanobis

In [189]:
cov = np.cov(Xc1.T)
inv1 = np.linalg.inv(cov)
print(inv1)

[[ 0.24090917 -0.04444754 -0.05888884  0.01667788  0.00219592 -0.04308261
  -0.0128902  -0.01477241 -0.02417398]
 [-0.04444754  0.759459   -0.45930565 -0.06509149 -0.15591478  0.01351662
  -0.11669806 -0.03639994 -0.03095096]
 [-0.05888884 -0.45930565  0.72326742 -0.0054962  -0.03971984 -0.06329771
  -0.02966834 -0.06280375 -0.00085625]
 [ 0.01667788 -0.06509149 -0.0054962   0.29694155 -0.02465248 -0.06508981
  -0.06723626 -0.02069857 -0.04447548]
 [ 0.00219592 -0.15591478 -0.03971984 -0.02465248  0.52696741 -0.02181746
  -0.00769176 -0.04681091 -0.09527598]
 [-0.04308261  0.01351662 -0.06329771 -0.06508981 -0.02181746  0.19010304
  -0.0629727   0.00353154  0.00431797]
 [-0.0128902  -0.11669806 -0.02966834 -0.06723626 -0.00769176 -0.0629727
   0.4790827  -0.06907704  0.04685202]
 [-0.01477241 -0.03639994 -0.06280375 -0.02069857 -0.04681091  0.00353154
  -0.06907704  0.25871233 -0.03680485]
 [-0.02417398 -0.03095096 -0.00085625 -0.04447548 -0.09527598  0.00431797
   0.04685202 -0.036804

In [193]:
E=calmdist(Xc1,Xc_t1,inv1)
n= dissort(E)
t1=predict(n,Yc1)
print(t1)
s1 = accur(t1,Yc_t1)
print(s1)

[array([2]), array([2]), array([2]), array([2]), array([2]), array([4]), array([2]), array([2]), array([4]), array([4]), array([2]), array([2]), array([2]), array([2]), array([4]), array([2]), array([2]), array([2]), array([2]), array([4])]
20
95.0


# Dataset 3

In [105]:
Y=[]
o=[]
p=[]
e=[]
f = open("Biodegradation/biodeg.csv", "r")
b=f.readlines()
Xb1 = np.empty(0)
for j in range(len(b)):
    lens=len(b[j])
    s=b[j].split(";")
    o.append((b[j][:lens-4]))
    p.append((b[j][lens-4:lens-1]))

for u in p:
    if(u==';RB'):
        Y.append([1,0])
    else:
        Y.append([0,1])

x=[]
for u in o:
    t=u.split(";")
    x.append(t)
print(len(t))


for u in x:
    for b in u:
        if (b!=''):
            e.append(float(b))

X=np.array(e)
X=X.reshape(1029,41)
f.close()

42


In [104]:
Y1=[]
o=[]
p=[]
e=[]
f = open("Biodegradation/Test.txt", "r")
b=f.readlines()
for j in range(len(b)):
    lens=len(b[j])
    s=b[j].split(";")
    o.append((b[j][:lens-4]))
    p.append((b[j][lens-4:lens-1]))

for u in p:
    if(u==';RB'):
        Y1.append([1,0])
    else:
        Y1.append([0,1])

x=[]
for u in o:
    t=u.split(";")
    x.append(t)

i=0
for u in x:
    for b in u:
        if (b!=''):
            e.append(float(b))
e.append(0)
X1=np.array(e)
X1=X1.reshape(26,41)

f.close()

# Euclidean distance

In [107]:
l=caldist(X,X1)
m= dissort(l)
t=predict(m,Y)
print(t)
s = accur(t,Y1)
print(s)

[array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]])]
26
96.15384615384616


# Mahalonbis distance 

In [109]:
cov = np.cov(X.T)
inv2 = np.linalg.inv(cov)
print(inv2)

[[ 90.80199796  -1.39342636  -2.13904133 ...  17.3518724   -1.27126149
    0.78859067]
 [ -1.39342636   5.93201022   0.3454768  ...  -2.41466093   0.93289537
   -1.21837931]
 [ -2.13904133   0.3454768    4.98619162 ...   0.14162162   0.6833829
   -2.6333971 ]
 ...
 [ 17.3518724   -2.41466093   0.14162162 ... 119.06578138   0.83113555
    0.45765851]
 [ -1.27126149   0.93289537   0.6833829  ...   0.83113555  12.82862085
   -0.83797346]
 [  0.78859067  -1.21837931  -2.6333971  ...   0.45765851  -0.83797346
    4.03189169]]


In [113]:
E=calmdist(X,X1,inv2)
n= dissort(E)
t1=predict(n,Y)
print(t1)
s1 = accur(t1,Y1)
print(s1)

[array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]])]
26
96.15384615384616


# Minowski

In [115]:
l=caldistmin(X,X1,10)
m= dissort(l)
t=predict(m,Y)
print(t)
s = accur(t,Y1)
print(s)

[array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[0, 0]]), array([[1, 0]]), array([[1, 0]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]])]
26
92.3076923076923


In [116]:
l=caldistmin(X,X1,1)
m= dissort(l)
t=predict(m,Y)
print(t)
s = accur(t,Y1)
print(s)

[array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[0, 1]]), array([[1, 0]]), array([[1, 0]]), array([[1, 0]])]
26
96.15384615384616
